<?php
/**
 * Copyright © 2017 REES46, INC. All rights reserved.
 */
?>
<?php if (($_products = $block->getProductCollection()) && $_products->getSize()): ?>
    <div class="block widget block-new-products-images">
        <?php if ($block->getTitle()):?>
            <div class="block-title">
                <strong><?php /* @escapeNotVerified */ echo $block->getTitle() ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <ol class="product-items product-items-images">
                <?php foreach ($_products->getItems() as $_item): ?>
                    <li class="product-item">
                        <a class="product-item-photo" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                           title="<?php /* @escapeNotVerified */ echo $block->stripTags($_item->getName(), null, true) ?>">
                            <?php /* new_products_images_only_widget */ ?>
                            <?php echo $block->getImage($_item, 'new_products_images_only_widget')->toHtml(); ?>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>
