<?php
/**
 * Copyright © 2017 REES46, INC. All rights reserved.
 */
?>
<?php $data = $block->getData('settings'); ?>
<!-- BEGIN REES46 BLOCK <?php echo $data['module_id']; ?> -->
<script type="text/javascript">
<?php echo $data['css']; ?>
r46('recommend', '<?php echo $data['type']; ?>', <?php echo $data['params']; ?>, function(results) {
    if (results.length > 0) {
        require(['jquery'], function($) {
            $('#rees46-recommended-<?php echo $data['module_id']; ?>').load('<?php echo $block->getBaseUrl(); ?>rees46/ajax/products?<?php echo http_build_query($data); ?>&product_ids=' + results);
        });
    }
});
</script>
<div id="rees46-recommended-<?php echo $data['module_id']; ?>"></div>
<!-- END REES46 BLOCK <?php echo $data['module_id']; ?> -->