<?php
/**
 * Copyright © 2017 REES46, INC. All rights reserved.
 */
?>
<style>
#rees46_auth_block + .section-config, #rees46_auth_block + div + .section-config {
    display: none;
}
.rees46-enabled-icon:before {
    font-family: 'Admin Icons';
    font-size: 1.5rem;
    color: #79a22e;
    content: '\e62d';
}
.rees46-disabled-icon:before {
    font-family: 'Admin Icons';
    font-size: 1.5rem;
    color: #a79d95;
    content: '\e62f';
}
</style>